### ISSUE TITLE
shorter table window

### ISSUE THREAD

**Issue by ChrisBup** [RadishLab/NAS011#3]
Always showing header and footer bars as user scrolls the table.

This would negate the need for sticky headers/footers as the user scrolled, right? Because a given table would always be in view, with height set to 400px or something. I'm thinking we'd enable scrolljacking on all tables (either automatically or on click) so that each table would be scrolled independently of page scroll. This might also negate the need to hide tables away in drawers which might help a bit with load time and streamline UI.

**estimate: 4 hours**

**Comment by Lhgordon** [comment]
@ChrisBup But the left hand column of the table needs to be in view as well.  The client had said they want to explore ability to freeze frame in both directions, while it still being smooth to scroll. 

They also said "can there be sliders on the x axis and the y axis and limit the rows that are visible (nobody needs to see all of the rows together. What need to be fixed are just the totals, and have the ability to scroll down with a limit to 5 states or so).
